FROM alpine@3.2

ENV http_proxy=http://proxy.***REMOVED***:8080 \
    https_proxy=http://proxy.***REMOVED***:8080 \
    no_proxy=***REMOVED***,localhost,127.0.0.1

RUN apk --update add alpine-sdk
ADD build.key.pub /etc/apk/keys/
ADD build.key /home/build/.abuild/build.key
RUN apk --update add openssl-dev c-ares-dev util-linux-dev libwebsockets-dev
ADD abuild.conf /etc/
RUN adduser -D build && addgroup build abuild
USER build
WORKDIR /home/build
ADD mosquitto/* /home/build/
CMD abuild -f
